### ISSUE TITLE
Bones won't wiggle

### ISSUE THREAD

**Issue by oddhorse** [shteeve3d/blender-wiggle-2#12]
I'm currently doing some animation with NLA strips and multiple scenes using a single character rig. In the scene I created this character in, Wiggle 2 works just fine. In another scene I linked the character rig into, Wiggle 2 does not drive any bone movement. I have a pretty messy NLA timeline, but this directly shouldn't be the issue since it works just fine played back in the first scene.

Here's my blend file, if this helps: https://drive.google.com/file/d/1sRFMap6N9tiCPK6YEi5WY4V9E7esoDz3/view?usp=sharing
I'm using Blender 3.5.1.

**Comment by shteeve3d** [comment]
i did a little debugging, and it looks like an internal variable that pauses the wiggle calculations when rendering (it causes instability otherwise) had somehow gotten stuck in your BUS STOP scene. generally it should turn itself off when a rendering finishes or is cancelled, but i guess there is the possibility of some edge case getting through.

what i might do is have a function that resets the rendering variable whenever a scene is reloaded to help minimize the issue. What you can do to fix it right now, is go to the problematic scene, and in the blender python console in the scripting tab type:

C.scene.wiggle.is_rendering = False

and see if that gets things wiggling again!

**Comment by shteeve3d** [comment]
I included a workaround in the latest release to make it easier to recover from this issue. See the release notes here for more info:
https://github.com/shteeve3d/blender-wiggle-2/releases/tag/v2.2.1
