### ISSUE TITLE
Wiggle bones keep freaking out

### ISSUE THREAD

**Issue by verygladen** [shteeve3d/blender-wiggle-2#17]
I've been trying to fix this for awhile, but I honestly have no clue what's causing it. The left hair keeps freaking out when enabled, but if i enable the other hair, its fine. Any clue why this is happening? 

Using Blender 3.5.1

https://github.com/shteeve3d/blender-wiggle-2/assets/37459940/9ff25bd9-2e0b-4c4b-beb8-daded9c463a7

**Comment by shteeve3d** [comment]
Hard to tell without looking into the details of the rig. My first guess was maybe the quality steps were too low, which reduces the influence bone wiggles have on each other - although odd if a similar hair chain on the other side is working ok? another thing to check is if the “chain” option is ticked on the problematic bones, since is also necessary for realistic physics on chains of bones.

**Comment by verygladen** [comment]
I checked and the chain option is enabled. The weights are almost pretty much the same too.

**Comment by shteeve3d** [comment]
are you able to share a copy of the scene? you can strip out your model or anything else other than the problematic bone setup (would be helpful to include the hair bones that are working as intended for comparison too)

**Comment by shteeve3d** [comment]
thanks!

i took a look and the issue seems to be that the problematic hair bones have their tails pointing in the wrong direction, so when you animated the tail wiggle, its all over the place.
<img width="798" alt="Screenshot 2023-06-12 at 2 10 47 PM" src="https://github.com/shteeve3d/blender-wiggle-2/assets/126594110/88d3886c-ce6c-43b0-9725-407f797a920f">

i did a quick edit on the rig to fix the direction, and the wiggle behaves as intended (although no collisions have been set up yet so the hair passes through the body):
https://drive.google.com/file/d/1R2kQ3dwr54oa_vKlFjIGjiod61aCUU5F/view?usp=sharing
https://drive.google.com/file/d/1Qg7xOazrVheaj4z1WDQMXWMYNPye-b_-/view?usp=sharing
