### ISSUE TITLE
Crash at the end of a render EXCEPTION_ACCESS_VIOLATION 

### ISSUE THREAD

**Issue by tsun3doku** [shteeve3d/blender-wiggle-2#24]
For the last few days I have been dealing with a lot of weird crashes and bugs at the end of a render that I couldn't pinpoint until I removed this addon. I don't know if its incompatible with hair particles but at first when I had used a larger tile set the render would crash at the end of the first frame, lowering it would result in a crash at the end of the 2nd frame and now completely removing the addon results in no crashes.
This was the error I was getting
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF7753EA16F
Module  : blender.exe
Thread  : 00000674

Some kind of memory issue. Happened with CPU and GPU rendering.

**Comment by shteeve3d** [comment]
ack. that is no good. had you updated to the 2.2.2 version of the addon (just to help me troubleshoot if the recent update to deal with multiple view layers might have caused this)

also have you tried checking "lock interface" in the dropdown of the top menubar to see if that stops the crashing?

**Comment by tsun3doku** [comment]
I am using 2.2.2 and checked lock interface. I think it has more to do with the amount of keyframes it generates. I noticed I still get crashes when my scene gets more complex with hair particles but the crashes stopped when I also got rid of the wiggle animation that gets attached to armature. I noticed that my gpu spikes to 100% when the 2nd frame gets rendered then crashes. Perhaps my hardware just can't handle it, I am using a 980ti which is a bit old.

**Comment by shteeve3d** [comment]
hmm, python scripts don't tend to use the gpu to my understanding, although when i googled that error i did see reports tied to the gpu, but that could be because its happening on the render process in general.

just to clarify, you're baking the wiggle effect to keyframes and then attempting to render, right? (which would indeed suggest its not an addon issue directly) in theory once you baked to keyframes you could disable the addon anyway to ensure it doesn't interfere with the render.

lastly, if it is the case that you baked to keyframes and its the number of those keyframes thats causing the issue on your system, have you tired the decimate keyframe operator to see if you can preserve the motion with fewer keys?

**Comment by tsun3doku** [comment]
I think this issue should be closed because I am starting to believe the ultimate cause of the crashes is another addon that I am using (turbotools). I've been dealing with this issue for over a week and I am really not getting any closer to resolving it. Removing this addon seemed to have fixed things at first but when I am crashing even after deleting the original armature and using an alembic then its likely a different issue entirely
